[package]
name = "grbl_cli"
version = "0.1.0"
authors = ["bumblepie <luke@bumblepie.space>"]

[dependencies]
serial = "0.4.0"
grbl = { path = "grbl" }
clap = {version = "~2.29.0", features = ["yaml"]}

[workspace]
